/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeighbridgeRouteImport } from './routes/weighbridge'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'

const WeighbridgeRoute = WeighbridgeRouteImport.update({
  id: '/weighbridge',
  path: '/weighbridge',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dispatch': typeof DispatchRoute
  '/drivers': typeof DriversRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/suppliers': typeof SuppliersRoute
  '/trips': typeof TripsRoute
  '/vehicles': typeof VehiclesRoute
  '/weighbridge': typeof WeighbridgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dispatch': typeof DispatchRoute
  '/drivers': typeof DriversRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/suppliers': typeof SuppliersRoute
  '/trips': typeof TripsRoute
  '/vehicles': typeof VehiclesRoute
  '/weighbridge': typeof WeighbridgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dispatch': typeof DispatchRoute
  '/drivers': typeof DriversRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/suppliers': typeof SuppliersRoute
  '/trips': typeof TripsRoute
  '/vehicles': typeof VehiclesRoute
  '/weighbridge': typeof WeighbridgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/dispatch'
    | '/drivers'
    | '/orders'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/suppliers'
    | '/trips'
    | '/vehicles'
    | '/weighbridge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/dispatch'
    | '/drivers'
    | '/orders'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/suppliers'
    | '/trips'
    | '/vehicles'
    | '/weighbridge'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/dispatch'
    | '/drivers'
    | '/orders'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/suppliers'
    | '/trips'
    | '/vehicles'
    | '/weighbridge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  DispatchRoute: typeof DispatchRoute
  DriversRoute: typeof DriversRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  SuppliersRoute: typeof SuppliersRoute
  TripsRoute: typeof TripsRoute
  VehiclesRoute: typeof VehiclesRoute
  WeighbridgeRoute: typeof WeighbridgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weighbridge': {
      id: '/weighbridge'
      path: '/weighbridge'
      fullPath: '/weighbridge'
      preLoaderRoute: typeof WeighbridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  DispatchRoute: DispatchRoute,
  DriversRoute: DriversRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  SuppliersRoute: SuppliersRoute,
  TripsRoute: TripsRoute,
  VehiclesRoute: VehiclesRoute,
  WeighbridgeRoute: WeighbridgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
